Use local settings instead of hardcoded paths.
+ Add template for local settings.
+ Add local settings (not template) to `.gitignore`.
+ Add documentation to `README.md`.
+ Load settings in scripts instead of hardcoded variables.

diff --git a/bin/migrate b/bin/migrate
--- a/bin/migrate
+++ b/bin/migrate
@@ -9,22 +9,24 @@ set -e
 set -u
 
 # Settings
-# TODO Get these from configuration file
-sourcePath=/home/benn/rwahs/source
-workPath=/home/benn/rwahs/work
-targetPath=/home/benn/rwahs/target
+localSettings="$(readlink -f $(dirname $(dirname ${0})))/local-settings"
+if [ ! -f "${localSettings}" ]; then
+	echo "Local settings file not found: ${localSettings}" >&2
+	exit 1
+fi
+source "${localSettings}"
 
 # Ensure source database and images exists
 if [ ! -d "${sourcePath}" ]; then
-	echo "Source path directory not found: ${sourcePath}" &>2
+	echo "Source path directory not found: ${sourcePath}" >&2
 	exit 1
 fi
 if [ ! -f "${sourcePath}/RWAHSBookshop_be.accdb" ]; then
-    echo "Access database file not found: ${sourcePath}/RWAHSBookshop_be.accdb" &>2
+    echo "Access database file not found: ${sourcePath}/RWAHSBookshop_be.accdb" >&2
     exit 1
 fi
 if [ ! -d "${sourcePath}/images" ]; then
-    echo "Access database file not found: ${sourcePath}/images" &>2
+    echo "Access database file not found: ${sourcePath}/images" >&2
     exit 1
 fi
 
diff --git a/bin/reset-db b/bin/reset-db
--- a/bin/reset-db
+++ b/bin/reset-db
@@ -9,10 +9,12 @@ set -e
 set -u
 
 # Settings
-# TODO Get these from configuration file
-dbauth=-uroot
-dbhost=
-dbname=magento2
+localSettings="$(readlink -f $(dirname $(dirname ${0})))/local-settings"
+if [ ! -f "${localSettings}" ]; then
+	echo "Local settings file not found: ${localSettings}" >&2
+	exit 1
+fi
+source "${localSettings}"
 
 # Reset the database using the current seed
 mysqladmin ${dbauth} ${dbhost} -f drop "${dbname}"
